parameters:
     digitas_strategy_content_selector_bundle.id_strategy_selector_manager.class: Digitas\Bundle\StrategyContentSelectorBundle\Manager\StrategyIdSelectorManager

services:
    digitas_strategy_content_selector_bundle.id_strategy_selector_manager:
       class: %digitas_strategy_content_selector_bundle.id_strategy_selector_manager.class%
       arguments: []