parameters:
     digitas_strategy_content_selector_bundle.id_strategy_selector_manager.class: Digitas\Bundle\StrategyContentSelectorBundle\Manager\StrategyIdSelectorManager

services:
     digitas_form_course.strategy_selector.symfony_validation:
         class: Digitas\Bundle\StrategyContentSelectorBundle\StrategySelector\SymfonyValidationStrategySelector
         arguments: [@validator]
         tags:
             - { name: strategy_selector.extension_subscriber }

    digitas_strategy_content_selector_bundle.id_strategy_selector_manager:
       class: %digitas_strategy_content_selector_bundle.id_strategy_selector_manager.class%
       arguments: [@service_container]

    digitas_strategy_content_selector_bundle.strategy_selector.calculateur_tarifs:
       class: Digitas\Bundle\StrategyContentSelectorBundle\StrategySelector\CalculateurTarifsStrategySelector
       tags:
           - { name: strategy_selector.extension_subscriber }